Traceback (most recent call last):
  File "CSFCamera.py", line 9, in <module>
    for filename in camera.capture_continuous('Pictures/img{timestamp:%Y-%m-%d-%H-%M-%S}.jpg'):
  File "/usr/lib/python2.7/dist-packages/picamera/camera.py", line 1691, in capture_continuous
    encoder.start(filename)
  File "/usr/lib/python2.7/dist-packages/picamera/encoders.py", line 1126, in start
    super(PiCookedOneImageEncoder, self).start(output)
  File "/usr/lib/python2.7/dist-packages/picamera/encoders.py", line 375, in start
    self._open_output(output)
  File "/usr/lib/python2.7/dist-packages/picamera/encoders.py", line 331, in _open_output
    self.outputs[key] = mo.open_stream(output)
  File "/usr/lib/python2.7/dist-packages/picamera/mmalobj.py", line 344, in open_stream
    stream = io.open(stream, 'wb' if output else 'rb', buffering)
IOError: [Errno 2] No such file or directory: 'Pictures/img2022-02-24-15-48-25.jpg'
Traceback (most recent call last):
  File "CSFCamera.py", line 9, in <module>
    for filename in camera.capture_continuous('Pictures/img{timestamp:%Y-%m-%d-%H-%M-%S}.jpg'):
  File "/usr/lib/python2.7/dist-packages/picamera/camera.py", line 1691, in capture_continuous
    encoder.start(filename)
  File "/usr/lib/python2.7/dist-packages/picamera/encoders.py", line 1126, in start
    super(PiCookedOneImageEncoder, self).start(output)
  File "/usr/lib/python2.7/dist-packages/picamera/encoders.py", line 375, in start
    self._open_output(output)
  File "/usr/lib/python2.7/dist-packages/picamera/encoders.py", line 331, in _open_output
    self.outputs[key] = mo.open_stream(output)
  File "/usr/lib/python2.7/dist-packages/picamera/mmalobj.py", line 344, in open_stream
    stream = io.open(stream, 'wb' if output else 'rb', buffering)
IOError: [Errno 2] No such file or directory: 'Pictures/img2022-03-19-15-31-38.jpg'
Capured /home/pi/Pictures/img2022-03-19-15-33-42.jpg
Capured /home/pi/Pictures/img2022-03-19-15-34-01.jpg
Capured /home/pi/Pictures/img2022-03-19-15-34-19.jpg
Traceback (most recent call last):
  File "CSFCamera.py", line 11, in <module>
    sleep(18)
KeyboardInterrupt
Capured /home/pi/Pictures/img2022-03-19-15-36-51.jpg
Traceback (most recent call last):
  File "CSFCamera.py", line 11, in <module>
    sleep(18)
KeyboardInterrupt
CSFCamera.py:13: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(solenoid, GPIO.OUT)
usage: CSFCamera.py [-h] --Frequency FREQUENCY --DutyCycle DUTYCYCLE
CSFCamera.py: error: the following arguments are required: --Frequency, --DutyCycle
CSFCamera.py:13: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(solenoid, GPIO.OUT)
Capured /home/pi/Pictures/img2022-04-19-12-22-01.jpg
17.5
17.0
16.5
16.0
15.5
15.0
14.5
14.0
13.5
13.0
12.5
12.0
11.5
11.0
10.5
10.0
9.5
9.0
8.5
8.0
7.5
7.0
6.5
6.0
5.5
5.0
Traceback (most recent call last):
  File "CSFCamera.py", line 43, in <module>
    sleep((period-dutyCycle))
KeyboardInterrupt
CSFCamera.py:13: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(solenoid, GPIO.OUT)
Capured /home/pi/Pictures/img2022-04-19-12-24-46.jpg
Traceback (most recent call last):
  File "CSFCamera.py", line 41, in <module>
    sleep(dutyCycle)
KeyboardInterrupt
Capured /home/pi/Pictures/img2022-04-20-06-40-18.jpg
Capured /home/pi/Pictures/img2022-04-20-06-40-28.jpg
Capured /home/pi/Pictures/img2022-04-20-06-40-38.jpg
Traceback (most recent call last):
  File "CSFCamera.py", line 50, in <module>
    sleep(period)
KeyboardInterrupt
